apiVersion: apps/v1
kind: Deployment
metadata:
  name:  currencyservice
  labels:
    app:  currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  replicas: 1
  template:
    metadata:
      labels:
        app:  currencyservice
    spec:
      containers:
      - name:  currencyservice
        image:  ashmil/democurrencyservice:latest
        env:
        - name: KEY
          value: "92b413765703a8b7ad401b1a39123453"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  5000
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  selector:
    app: currencyservice
  ports:
  - port: 80
    targetPort: 5000